name: Deploy Next.js site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js
        run: npm run build
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .next